### ISSUE TITLE
License for reuse

### ISSUE THREAD

**Issue by joshforman** [kodin21/chat-app-team-c#3]
I'm curious if you'd license this repo for reuse?  I'm working on a personal chat project and this is kind of the perfect design for what I was looking for.

If you would be willing to make some minor modifications to the design I'd also be happy to pay you for the trouble!

**Comment by yusufcmlt** [comment]
You can use it anyway you want but i don't have the time for modifications right now. @joshforman

**Comment by onur-yuksekkaya** [comment]
We added license 👍

**Comment by joshforman** [comment]
Many thanks from the United States :)
